{{- $serviceName := include "member-go.name" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
type: Opaque
data:
{{- $v := $.Files.Get "secret/postgres.yaml" | fromYaml }}
{{- range $key,$val := $v }}
{{ $key | indent 2 }}: {{ $val | b64enc }}
{{- end}}