replicaCount: 1

image:
  repository: 9ilbert/member-go
  pullPolicy: Always
  tag: "amd-0.0"

application:
  profile: ''
  server:
    port: 8080

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

rollout:
  strategy: bluegreen
  autoPromotionEnabled: true

# livenessProbe:
#   httpGet:
#     path: /members
#     port: 8080
# readinessProbe:
#   httpGet:
#     path: /members
#     port: 8080

serviceAccount:
  annotations: {}

pinpoint:
  enabled: false
  version: 2.5.1
