{{- $serviceName := include "member.name" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $serviceName }}-vsvc
spec:
  hosts:
  - {{ .Values.hostName }}
  gateways:
  - msa-gateway
  http:
    - name: primary
      {{- if eq .Values.rollout.strategy "canary" }}
      route:
      - destination:
          host: {{ $serviceName }}
          subset: stable
          port:
            number: {{ .Values.service.targetport }}
        weight: 50
      - destination:
          host: {{ $serviceName }}
          subset: canary
          port:
            number: {{ .Values.service.targetport }}
        weight: 0
      - destination:
          host: {{ $serviceName }}-go
          subset: stable
          port:
            number: {{ .Values.service.targetport }}
        weight: 50
      - destination:
          host: {{ $serviceName }}-go
          subset: canary
          port:
            number: {{ .Values.service.targetport }}
        weight: 0        
      {{- else if eq .Values.rollout.strategy "bluegreen" }} 
      route:
      - destination:
          host: {{ $serviceName }}
          port:
            number: {{ .Values.service.targetport }}
        weight: 50
      - destination:
          host: {{ $serviceName }}-preview
          port:
            number: {{ .Values.service.targetport }}
        weight: 0
      - destination:
          host: {{ $serviceName }}-go
          port:
            number: {{ .Values.service.targetport }}
        weight: 50
      - destination:
          host: {{ $serviceName }}-go-preview
          port:
            number: {{ .Values.service.targetport }}
        weight: 0        
      {{- end }}